### ISSUE TITLE
Empty box shows when Show Background is enabled

### ISSUE THREAD

**Issue by Zylph** [MidoriKami/CurrencyAlert#1]
When the option for "Show Background" is enabled, it shows an empty box with the color of the background, even when there are currently no currencies over alert threshold. 

![image](https://github.com/MidoriKami/CurrencyAlert/assets/42854982/7505f56c-a7ab-41dd-b325-6a145e5a9c62)

![image](https://github.com/MidoriKami/CurrencyAlert/assets/42854982/f3e52b79-ed8d-444b-9996-fe417b522702)

![image](https://github.com/MidoriKami/CurrencyAlert/assets/42854982/90d407da-cab3-4440-b257-65f787a8ca86)

**Comment by MidoriKami** [comment]
Already fixed in e41a7e7
Just waiting update merge to dalamud.

Thanks for the report.
