### ISSUE TITLE
Warning Background Color always opaque black

### ISSUE THREAD

**Issue by SnoFox** [MidoriKami/CurrencyAlert#13]
No matter what options or alpha I choose, the text overlay (not list background color) is an opaque black.

In my examples below, I expect the box around "Allagan Tomestone of Poetics" to be a transparent blue, given the settings

![image](https://github.com/user-attachments/assets/0067afe6-cc1f-4703-971f-e2644e57912b)
![image](https://github.com/user-attachments/assets/d723a38a-8e49-484f-8e0a-d7965ab899c5)

**Comment by MidoriKami** [comment]
Change the "Warning Background Color"

**Comment by MidoriKami** [comment]
Upon further investigation there does seem something weird going on
