### ISSUE TITLE
missing crafting and gathering scrips?

### ISSUE THREAD

**Issue by jacob-keller** [MidoriKami/CurrencyAlert#14]
I don't see a way to track the purple and orange crafting and gathering scrips currently

**Comment by MidoriKami** [comment]
You can track literally any item in the game. (Currencies are actually just items).


https://github.com/user-attachments/assets/d9ab4e44-0a85-4f02-90b2-c296947c7369

**Comment by jacob-keller** [comment]
Hmmm I will check again, I tried searching for the item but it didn't seem to show up. Sorry about the noise

**Comment by MidoriKami** [comment]
As shown it's `Scrip` not `Script` 👍
