### ISSUE TITLE
Not displaying

### ISSUE THREAD

**Issue by Mephistou** [MidoriKami/CurrencyAlert#2]
After I got a new PC currency alert UI is gone, checked out all the settings idk maybe I'm missing something.

**Comment by MidoriKami** [comment]
Check your settings again, you need to enable the overlay, then each currency you want to show in the overlay must both be enabled and have the `overlay` option checked.

**Comment by Mephistou** [comment]
oh ty I finally got it to display but It shows"xxx is above treshold" while before it was "You need to spend your xxx" i want that one back
