### ISSUE TITLE
Anchor on Right for the overlay doesn't work

### ISSUE THREAD

**Issue by Error-Error-Error** [MidoriKami/CurrencyAlert#20]
Hi.
Anchoring to the right (Top Right, Bottom Right) causes the entire entry to disappear if Clip Content is checked. If unchecked, the overlay will appear to the right of the box, and still anchored Left, just outside the box now.

![04](https://github.com/user-attachments/assets/72b460a9-5718-4679-af2b-c012d184b904)

**Comment by MidoriKami** [comment]
Reason is the same that caused #18 so marking this as duplicate
