### ISSUE TITLE
[feature request] persistent overlay

### ISSUE THREAD

**Issue by hhharkness** [MidoriKami/CurrencyAlert#24]
hi! i would love an option to keep the overlay always showing as it's a great way to keep track of how much you have of each currency, but still get a warning when they're capped. easiest implementation would probably be either just adding a checkbox for always showing the overlay or allowing separate thresholds for overlay and chat warnings, but my dream solution would be an option to have the item count text colour change - ideally twice so i could set it to be orange when close to cap and red when capped. thanks!

**Comment by MidoriKami** [comment]
That is not in line with the intent of this plugin. 

If you want a persistent display of currencies, use my Expanded Currency Display tweak in SimpleTweaks.

**Comment by hhharkness** [comment]
i had completely missed that tweak, thank you for letting me know! is there any chance it could include an option to have the layout look like this one though? it's so much easier to read and also takes up less space!
