### ISSUE TITLE
Suggestion: Option to change overlay anchor point

### ISSUE THREAD

**Issue by Azekthi** [MidoriKami/CurrencyAlert#3]
Right now, the overlay is anchored to the top-left corner, meaning that currencies will expand the overlay to the right and down. I'd like an option to change which corner is used as the anchor point i.e. if the bottom-right corner was selected, the overlay would expand to the left and up, and so on.

**Comment by MidoriKami** [comment]
I attempted to implement these features but they ended up taking an inordinate amount of time and didn't work quite right.

These features are not planned to be added to CurrencyAlert.
PR's are welcome.
