### ISSUE TITLE
Expand notification, modifiable text string

### ISSUE THREAD

**Issue by blitzmikyu** [MidoriKami/CurrencyAlert#6]
Hello, I would like to see the ability to customize the text string to show not only that the currency has reached the threshold but also show the amount of currency and possibly the cap. This could apply to both overlay or chat echo. Maybe the echo could also show as one line instead one line for each alert.

**Comment by MidoriKami** [comment]
I feel this clutters the UI too much. For tracking current quantities use the `ExpandedCurrencyDisplay` tweak from SimpleTweaks.

**Comment by MidoriKami** [comment]
I'll keep the request in mind, and if enough people are interested I may consider it.

**Comment by blitzmikyu** [comment]
Thanks for the suggestion, I have the GIL hud element off as I do not need to see my gil constantly or with the simpletweaks enhancement, to see all my currencies on my screen. Prefer a clean UI.

I primarily just want to see this enhancement for chat echos so I don't need to reference the currency window to see how much I actually do have. The string doesn't need to be customizable, but at least the option to display the amount in the chat echo would be exactly what I'm after.
